version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internet_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=internet_db
      - DB_USERNAME=internet_user
      - DB_PASSWORD=internet_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - internet_network

  db:
    image: mysql:8.0
    container_name: internet_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: internet_db
      MYSQL_USER: internet_user
      MYSQL_PASSWORD: internet_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - internet_network

  redis:
    image: redis:7-alpine
    container_name: internet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - internet_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: internet_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: internet_user
      PMA_PASSWORD: internet_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - internet_network

volumes:
  db_data:
  redis_data:

networks:
  internet_network:
    driver: bridge
