version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: internet-app
    restart: unless-stopped
    ports:
      - "1217:1217"
    environment:
      - APP_NAME=Internet Management
      - APP_ENV=production
      - APP_KEY=base64:${APP_KEY:-}
      - APP_DEBUG=false
      - APP_URL=http://localhost:1217
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=internet_management
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=log
      - LOG_CHANNEL=stack
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    networks:
      - internet-network
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1217/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: internet-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=internet_management
      - MYSQL_USER=internet_user
      - MYSQL_PASSWORD=internet_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internet-network
    ports:
      - "3306:3306"

networks:
  internet-network:
    driver: bridge

volumes:
  mysql_data:
  storage:
